version: 2.1


restore_bazel_cache: &restore_bazel_cache
  restore_cache:
    keys:
      - v4-bazel-cache-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ .Revision }}
      - v4-bazel-cache-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}
      - v4-bazel-cache-{{ .Environment.CIRCLE_JOB }}-main

save_bazel_cache: &save_bazel_cache
  save_cache:
    # Always saving the cache, even in case of failures, helps with completing
    # jobs where the bazel process was killed because it took too long or OOM.
    # Restart the job if you see the bazel server being terminated abruptly.
    when: always
    key: v4-bazel-cache-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ .Revision }}
    paths:
      - /tmp/bazel-cache
      - /tmp/bazel-disk-cache

clean_bazel_cache: &clean_bazel_cache
  run:
    name: Clean Bazel disk cache of files that have not been modified in 30 days
    # mtime is the only time preserved after untaring the cache.
    command: /usr/bin/find /tmp/bazel-disk-cache -mtime +30 -exec rm -v {} \;

set_bazelrc: &set_bazelrc
  run:
    name: Set bazelrc
    command: cat .circleci/bazelrc >> .bazelrc

install_bazel: &install_bazel
  run:
    name: Install bazel
    command: |
      curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
      mkdir -p bin
      mv bazelisk-linux-amd64 bin/bazel
      chmod +x bin/bazel
jobs:
  publish-linux-amd64-beacon-chain-binary:
    docker:
      - image: cimg/base:2023.09
    #resource_class: xlarge
    steps:
      - checkout
      - *install_bazel
      - *restore_bazel_cache
      - *set_bazelrc
      - run: |
          rm -rf /tmp/bazel-cache/output-root/install
          
          bin/bazel build --config=release --config=linux_amd64 --define=blst_modern=false //cmd/beacon-chain //cmd/validator
          
          cp bazel-bin/cmd/beacon-chain/beacon-chain_/beacon-chain /tmp/beacon-chain-${CIRCLE_TAG}-linux-amd64
          cp bazel-bin/cmd/validator/validator_/validator /tmp/validator-${CIRCLE_TAG}-linux-amd64

          (cd /tmp && sha256sum beacon-chain-${CIRCLE_TAG}-linux-amd64 > beacon-chain-${CIRCLE_TAG}-linux-amd64.sha256)
          (cd /tmp && sha256sum validator-${CIRCLE_TAG}-linux-amd64 > validator-${CIRCLE_TAG}-linux-amd64.sha256)

          # TODO(rgeraldes24): replace default key --default-key 0AE0051D647BA3C1A917AF4072E33E4DF1A5036E 
          # TODO(rgeraldes24): remove as soon as the key is available in the machine
          gpg --full-gen-key --batch <(echo "Key-Type: 1"; \
                             echo "Key-Length: 4096"; \
                             echo "Subkey-Type: 1"; \
                             echo "Subkey-Length: 4096"; \
                             echo "Expire-Date: 0"; \
                             echo "Name-Real: Root Superuser"; \
                             echo "Name-Email: root@handbook.westarete.com"; \
                             echo "%no-protection"; )
          gpg -o /tmp/beacon-chain-${CIRCLE_TAG}-linux-amd64.sig --sign --detach-sig /tmp/beacon-chain-${CIRCLE_TAG}-linux-amd64
          gpg -o /tmp/validator-${CIRCLE_TAG}-linux-amd64.sig --sign --detach-sig /tmp/validator-${CIRCLE_TAG}-linux-amd64

          # TODO(rgeraldes24): change owner to 'theQRL' and repo to 'qrysm' and tag to ${CIRCLE_TAG}
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/beacon-chain-${CIRCLE_TAG}-linux-amd64
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/beacon-chain-${CIRCLE_TAG}-linux-amd64.sha256
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/beacon-chain-${CIRCLE_TAG}-linux-amd64.sig
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/validator-${CIRCLE_TAG}-linux-amd64
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/validator-${CIRCLE_TAG}-linux-amd64.sha256
          ./hack/upload-github-release-asset.sh github_api_token=$GITHUB_TOKEN owner=rgeraldes24 repo=prysm tag=v0.1.0 filename=/tmp/validator-${CIRCLE_TAG}-linux-amd64.sig
      - *clean_bazel_cache
      - *save_bazel_cache

  # publish-windows-amd64-beacon-chain-binary:
  #   docker:
  #    - image: cimg/base:2023.09
  #   #resource_class: xlarge
  #   steps:
  #     - checkout
  #     - setup_remote_docker:
  #         version: 20.10.14
  #         docker_layer_caching: true
  #     - run: |
  #         curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
  #         mkdir -p bin
  #         mv bazelisk-linux-amd64 bin/bazel
  #         chmod +x bin/bazel
  #     - run: |
  #         bin/bazel build --config=release --config=windows_amd64_docker  //cmd/beacon-chain
  #         cp bazel-bin/cmd/beacon-chain/beacon-chain_/beacon-chain.exe bin/beacon-chain-${CIRCLE_TAG}-windows-amd64.exe
  #         ls bin
  #     - persist_to_workspace:
  #         root: bin
  #         paths:
  #           - beacon-chain-${CIRCLE_TAG}-windows-amd64.exe

  # publish-darwin-amd64-beacon-chain-binary:
  #   docker:
  #    - image: cimg/base:2023.09
  #   #resource_class: xlarge
  #   steps:
  #     - checkout
  #     - setup_remote_docker:
  #         version: 20.10.14
  #         docker_layer_caching: true
  #     - run: |
  #         curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
  #         mkdir -p bin
  #         mv bazelisk-linux-amd64 bin/bazel
  #         chmod +x bin/bazel
  #     - run: |
  #         bin/bazel build --config=release --config=osx_amd64_docker  //cmd/beacon-chain
  #         cp bazel-bin/cmd/beacon-chain/beacon-chain_/beacon-chain bin/beacon-chain-${CIRCLE_TAG}-darwin-amd64
  #         ls bin
  #     - persist_to_workspace:
  #         root: bin
  #         paths:
  #           - beacon-chain-${CIRCLE_TAG}-darwin-amd64

workflows:
  release:
    jobs:
      - publish-linux-amd64-beacon-chain-binary
      - publish-linux-arm64-beacon-chain-binary
      #- publish-windows-amd64-beacon-chain-binary
      #- publish-darwin-amd64-beacon-chain-binary
          # filters:
          #   tags:
          #     only: /^circlev.*/
          #     #only: /^v.*/
          #   # branches:
          #   #   ignore: /.*/