// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: proto/qrysm/v1alpha1/beacon_state.proto

package qrl

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	github_com_theQRL_go_bitfield "github.com/theQRL/go-bitfield"
	github_com_theQRL_qrysm_consensus_types_primitives "github.com/theQRL/qrysm/consensus-types/primitives"
	v1 "github.com/theQRL/qrysm/proto/engine/v1"
	_ "github.com/theQRL/qrysm/proto/qrl/ext"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Fork struct {
	state           protoimpl.MessageState                                   `protogen:"open.v1"`
	PreviousVersion []byte                                                   `protobuf:"bytes,1,opt,name=previous_version,json=previousVersion,proto3" json:"previous_version,omitempty" ssz-size:"4"`
	CurrentVersion  []byte                                                   `protobuf:"bytes,2,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty" ssz-size:"4"`
	Epoch           github_com_theQRL_qrysm_consensus_types_primitives.Epoch `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Epoch"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Fork) Reset() {
	*x = Fork{}
	mi := &file_proto_qrysm_v1alpha1_beacon_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fork) ProtoMessage() {}

func (x *Fork) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fork.ProtoReflect.Descriptor instead.
func (*Fork) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_state_proto_rawDescGZIP(), []int{0}
}

func (x *Fork) GetPreviousVersion() []byte {
	if x != nil {
		return x.PreviousVersion
	}
	return nil
}

func (x *Fork) GetCurrentVersion() []byte {
	if x != nil {
		return x.CurrentVersion
	}
	return nil
}

func (x *Fork) GetEpoch() github_com_theQRL_qrysm_consensus_types_primitives.Epoch {
	if x != nil {
		return x.Epoch
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Epoch(0)
}

type PendingAttestation struct {
	state           protoimpl.MessageState                                            `protogen:"open.v1"`
	AggregationBits github_com_theQRL_go_bitfield.Bitlist                             `protobuf:"bytes,1,opt,name=aggregation_bits,json=aggregationBits,proto3" json:"aggregation_bits,omitempty" cast-type:"github.com/theQRL/go-bitfield.Bitlist" ssz-max:"32"`
	Data            *AttestationData                                                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	InclusionDelay  github_com_theQRL_qrysm_consensus_types_primitives.Slot           `protobuf:"varint,3,opt,name=inclusion_delay,json=inclusionDelay,proto3" json:"inclusion_delay,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Slot"`
	ProposerIndex   github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex `protobuf:"varint,4,opt,name=proposer_index,json=proposerIndex,proto3" json:"proposer_index,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.ValidatorIndex"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PendingAttestation) Reset() {
	*x = PendingAttestation{}
	mi := &file_proto_qrysm_v1alpha1_beacon_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingAttestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingAttestation) ProtoMessage() {}

func (x *PendingAttestation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingAttestation.ProtoReflect.Descriptor instead.
func (*PendingAttestation) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_state_proto_rawDescGZIP(), []int{1}
}

func (x *PendingAttestation) GetAggregationBits() github_com_theQRL_go_bitfield.Bitlist {
	if x != nil {
		return x.AggregationBits
	}
	return github_com_theQRL_go_bitfield.Bitlist(nil)
}

func (x *PendingAttestation) GetData() *AttestationData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PendingAttestation) GetInclusionDelay() github_com_theQRL_qrysm_consensus_types_primitives.Slot {
	if x != nil {
		return x.InclusionDelay
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Slot(0)
}

func (x *PendingAttestation) GetProposerIndex() github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex {
	if x != nil {
		return x.ProposerIndex
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex(0)
}

type HistoricalBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockRoots    [][]byte               `protobuf:"bytes,1,rep,name=block_roots,json=blockRoots,proto3" json:"block_roots,omitempty" ssz-size:"1024,32"`
	StateRoots    [][]byte               `protobuf:"bytes,2,rep,name=state_roots,json=stateRoots,proto3" json:"state_roots,omitempty" ssz-size:"1024,32"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoricalBatch) Reset() {
	*x = HistoricalBatch{}
	mi := &file_proto_qrysm_v1alpha1_beacon_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoricalBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoricalBatch) ProtoMessage() {}

func (x *HistoricalBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoricalBatch.ProtoReflect.Descriptor instead.
func (*HistoricalBatch) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_state_proto_rawDescGZIP(), []int{2}
}

func (x *HistoricalBatch) GetBlockRoots() [][]byte {
	if x != nil {
		return x.BlockRoots
	}
	return nil
}

func (x *HistoricalBatch) GetStateRoots() [][]byte {
	if x != nil {
		return x.StateRoots
	}
	return nil
}

type StateSummary struct {
	state         protoimpl.MessageState                                  `protogen:"open.v1"`
	Slot          github_com_theQRL_qrysm_consensus_types_primitives.Slot `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Slot"`
	Root          []byte                                                  `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateSummary) Reset() {
	*x = StateSummary{}
	mi := &file_proto_qrysm_v1alpha1_beacon_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateSummary) ProtoMessage() {}

func (x *StateSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateSummary.ProtoReflect.Descriptor instead.
func (*StateSummary) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_state_proto_rawDescGZIP(), []int{3}
}

func (x *StateSummary) GetSlot() github_com_theQRL_qrysm_consensus_types_primitives.Slot {
	if x != nil {
		return x.Slot
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Slot(0)
}

func (x *StateSummary) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

type SigningData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectRoot    []byte                 `protobuf:"bytes,1,opt,name=object_root,json=objectRoot,proto3" json:"object_root,omitempty" ssz-size:"32"`
	Domain        []byte                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty" ssz-size:"32"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningData) Reset() {
	*x = SigningData{}
	mi := &file_proto_qrysm_v1alpha1_beacon_state_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningData) ProtoMessage() {}

func (x *SigningData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_state_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningData.ProtoReflect.Descriptor instead.
func (*SigningData) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_state_proto_rawDescGZIP(), []int{4}
}

func (x *SigningData) GetObjectRoot() []byte {
	if x != nil {
		return x.ObjectRoot
	}
	return nil
}

func (x *SigningData) GetDomain() []byte {
	if x != nil {
		return x.Domain
	}
	return nil
}

type ForkData struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	CurrentVersion        []byte                 `protobuf:"bytes,1,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty" ssz-size:"4"`
	GenesisValidatorsRoot []byte                 `protobuf:"bytes,2,opt,name=genesis_validators_root,json=genesisValidatorsRoot,proto3" json:"genesis_validators_root,omitempty" ssz-size:"32"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ForkData) Reset() {
	*x = ForkData{}
	mi := &file_proto_qrysm_v1alpha1_beacon_state_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkData) ProtoMessage() {}

func (x *ForkData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_state_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkData.ProtoReflect.Descriptor instead.
func (*ForkData) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_state_proto_rawDescGZIP(), []int{5}
}

func (x *ForkData) GetCurrentVersion() []byte {
	if x != nil {
		return x.CurrentVersion
	}
	return nil
}

func (x *ForkData) GetGenesisValidatorsRoot() []byte {
	if x != nil {
		return x.GenesisValidatorsRoot
	}
	return nil
}

type CheckPtInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seed          []byte                 `protobuf:"bytes,1,opt,name=seed,proto3" json:"seed,omitempty"`
	GenesisRoot   []byte                 `protobuf:"bytes,2,opt,name=genesis_root,json=genesisRoot,proto3" json:"genesis_root,omitempty"`
	ActiveIndices []uint64               `protobuf:"varint,3,rep,packed,name=active_indices,json=activeIndices,proto3" json:"active_indices,omitempty"`
	PubKeys       [][]byte               `protobuf:"bytes,4,rep,name=pub_keys,json=pubKeys,proto3" json:"pub_keys,omitempty"`
	Fork          *Fork                  `protobuf:"bytes,5,opt,name=fork,proto3" json:"fork,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPtInfo) Reset() {
	*x = CheckPtInfo{}
	mi := &file_proto_qrysm_v1alpha1_beacon_state_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPtInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPtInfo) ProtoMessage() {}

func (x *CheckPtInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_state_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPtInfo.ProtoReflect.Descriptor instead.
func (*CheckPtInfo) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_state_proto_rawDescGZIP(), []int{6}
}

func (x *CheckPtInfo) GetSeed() []byte {
	if x != nil {
		return x.Seed
	}
	return nil
}

func (x *CheckPtInfo) GetGenesisRoot() []byte {
	if x != nil {
		return x.GenesisRoot
	}
	return nil
}

func (x *CheckPtInfo) GetActiveIndices() []uint64 {
	if x != nil {
		return x.ActiveIndices
	}
	return nil
}

func (x *CheckPtInfo) GetPubKeys() [][]byte {
	if x != nil {
		return x.PubKeys
	}
	return nil
}

func (x *CheckPtInfo) GetFork() *Fork {
	if x != nil {
		return x.Fork
	}
	return nil
}

type DepositMessage struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PublicKey           []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty" spec-name:"pubkey" ssz-size:"2592"`
	WithdrawalRecipient []byte                 `protobuf:"bytes,2,opt,name=withdrawal_recipient,json=withdrawalRecipient,proto3" json:"withdrawal_recipient,omitempty" ssz-size:"64"`
	Amount              uint64                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	RandaoCommitment    []byte                 `protobuf:"bytes,4,opt,name=randao_commitment,json=randaoCommitment,proto3" json:"randao_commitment,omitempty" ssz-size:"32"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DepositMessage) Reset() {
	*x = DepositMessage{}
	mi := &file_proto_qrysm_v1alpha1_beacon_state_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositMessage) ProtoMessage() {}

func (x *DepositMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_state_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositMessage.ProtoReflect.Descriptor instead.
func (*DepositMessage) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_state_proto_rawDescGZIP(), []int{7}
}

func (x *DepositMessage) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *DepositMessage) GetWithdrawalRecipient() []byte {
	if x != nil {
		return x.WithdrawalRecipient
	}
	return nil
}

func (x *DepositMessage) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DepositMessage) GetRandaoCommitment() []byte {
	if x != nil {
		return x.RandaoCommitment
	}
	return nil
}

type SyncCommittee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkeys       [][]byte               `protobuf:"bytes,1,rep,name=pubkeys,proto3" json:"pubkeys,omitempty" ssz-size:"128,2592"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncCommittee) Reset() {
	*x = SyncCommittee{}
	mi := &file_proto_qrysm_v1alpha1_beacon_state_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncCommittee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncCommittee) ProtoMessage() {}

func (x *SyncCommittee) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_state_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncCommittee.ProtoReflect.Descriptor instead.
func (*SyncCommittee) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_state_proto_rawDescGZIP(), []int{8}
}

func (x *SyncCommittee) GetPubkeys() [][]byte {
	if x != nil {
		return x.Pubkeys
	}
	return nil
}

type SyncAggregatorSelectionData struct {
	state             protoimpl.MessageState                                  `protogen:"open.v1"`
	Slot              github_com_theQRL_qrysm_consensus_types_primitives.Slot `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Slot"`
	SubcommitteeIndex uint64                                                  `protobuf:"varint,2,opt,name=subcommittee_index,json=subcommitteeIndex,proto3" json:"subcommittee_index,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SyncAggregatorSelectionData) Reset() {
	*x = SyncAggregatorSelectionData{}
	mi := &file_proto_qrysm_v1alpha1_beacon_state_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAggregatorSelectionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAggregatorSelectionData) ProtoMessage() {}

func (x *SyncAggregatorSelectionData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_state_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAggregatorSelectionData.ProtoReflect.Descriptor instead.
func (*SyncAggregatorSelectionData) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_state_proto_rawDescGZIP(), []int{9}
}

func (x *SyncAggregatorSelectionData) GetSlot() github_com_theQRL_qrysm_consensus_types_primitives.Slot {
	if x != nil {
		return x.Slot
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Slot(0)
}

func (x *SyncAggregatorSelectionData) GetSubcommitteeIndex() uint64 {
	if x != nil {
		return x.SubcommitteeIndex
	}
	return 0
}

type BeaconStateZond struct {
	state                        protoimpl.MessageState                                            `protogen:"open.v1"`
	GenesisTime                  uint64                                                            `protobuf:"varint,1001,opt,name=genesis_time,json=genesisTime,proto3" json:"genesis_time,omitempty"`
	GenesisValidatorsRoot        []byte                                                            `protobuf:"bytes,1002,opt,name=genesis_validators_root,json=genesisValidatorsRoot,proto3" json:"genesis_validators_root,omitempty" ssz-size:"32"`
	Slot                         github_com_theQRL_qrysm_consensus_types_primitives.Slot           `protobuf:"varint,1003,opt,name=slot,proto3" json:"slot,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Slot"`
	Fork                         *Fork                                                             `protobuf:"bytes,1004,opt,name=fork,proto3" json:"fork,omitempty"`
	LatestBlockHeader            *BeaconBlockHeader                                                `protobuf:"bytes,2001,opt,name=latest_block_header,json=latestBlockHeader,proto3" json:"latest_block_header,omitempty"`
	BlockRoots                   [][]byte                                                          `protobuf:"bytes,2002,rep,name=block_roots,json=blockRoots,proto3" json:"block_roots,omitempty" ssz-size:"1024,32"`
	StateRoots                   [][]byte                                                          `protobuf:"bytes,2003,rep,name=state_roots,json=stateRoots,proto3" json:"state_roots,omitempty" ssz-size:"1024,32"`
	HistoricalRoots              [][]byte                                                          `protobuf:"bytes,2004,rep,name=historical_roots,json=historicalRoots,proto3" json:"historical_roots,omitempty" ssz-max:"16777216" ssz-size:"?,32"`
	ExecutionData                *ExecutionData                                                    `protobuf:"bytes,3001,opt,name=execution_data,json=executionData,proto3" json:"execution_data,omitempty"`
	ExecutionDataVotes           []*ExecutionData                                                  `protobuf:"bytes,3002,rep,name=execution_data_votes,json=executionDataVotes,proto3" json:"execution_data_votes,omitempty" ssz-max:"512"`
	ExecutionDepositIndex        uint64                                                            `protobuf:"varint,3003,opt,name=execution_deposit_index,json=executionDepositIndex,proto3" json:"execution_deposit_index,omitempty"`
	Validators                   []*Validator                                                      `protobuf:"bytes,4001,rep,name=validators,proto3" json:"validators,omitempty" ssz-max:"1099511627776"`
	Balances                     []uint64                                                          `protobuf:"varint,4002,rep,packed,name=balances,proto3" json:"balances,omitempty" ssz-max:"1099511627776"`
	RandaoMixes                  [][]byte                                                          `protobuf:"bytes,5001,rep,name=randao_mixes,json=randaoMixes,proto3" json:"randao_mixes,omitempty" ssz-size:"65536,32"`
	Slashings                    []uint64                                                          `protobuf:"varint,6001,rep,packed,name=slashings,proto3" json:"slashings,omitempty" ssz-size:"1024"`
	PreviousEpochParticipation   []byte                                                            `protobuf:"bytes,7001,opt,name=previous_epoch_participation,json=previousEpochParticipation,proto3" json:"previous_epoch_participation,omitempty" ssz-max:"1099511627776"`
	CurrentEpochParticipation    []byte                                                            `protobuf:"bytes,7002,opt,name=current_epoch_participation,json=currentEpochParticipation,proto3" json:"current_epoch_participation,omitempty" ssz-max:"1099511627776"`
	JustificationBits            github_com_theQRL_go_bitfield.Bitvector4                          `protobuf:"bytes,8001,opt,name=justification_bits,json=justificationBits,proto3" json:"justification_bits,omitempty" cast-type:"github.com/theQRL/go-bitfield.Bitvector4" ssz-size:"1"`
	PreviousJustifiedCheckpoint  *Checkpoint                                                       `protobuf:"bytes,8002,opt,name=previous_justified_checkpoint,json=previousJustifiedCheckpoint,proto3" json:"previous_justified_checkpoint,omitempty"`
	CurrentJustifiedCheckpoint   *Checkpoint                                                       `protobuf:"bytes,8003,opt,name=current_justified_checkpoint,json=currentJustifiedCheckpoint,proto3" json:"current_justified_checkpoint,omitempty"`
	FinalizedCheckpoint          *Checkpoint                                                       `protobuf:"bytes,8004,opt,name=finalized_checkpoint,json=finalizedCheckpoint,proto3" json:"finalized_checkpoint,omitempty"`
	InactivityScores             []uint64                                                          `protobuf:"varint,9001,rep,packed,name=inactivity_scores,json=inactivityScores,proto3" json:"inactivity_scores,omitempty" ssz-max:"1099511627776"`
	CurrentSyncCommittee         *SyncCommittee                                                    `protobuf:"bytes,9002,opt,name=current_sync_committee,json=currentSyncCommittee,proto3" json:"current_sync_committee,omitempty"`
	NextSyncCommittee            *SyncCommittee                                                    `protobuf:"bytes,9003,opt,name=next_sync_committee,json=nextSyncCommittee,proto3" json:"next_sync_committee,omitempty"`
	LatestExecutionPayloadHeader *v1.ExecutionPayloadHeaderZond                                    `protobuf:"bytes,10001,opt,name=latest_execution_payload_header,json=latestExecutionPayloadHeader,proto3" json:"latest_execution_payload_header,omitempty"`
	NextWithdrawalIndex          uint64                                                            `protobuf:"varint,11001,opt,name=next_withdrawal_index,json=nextWithdrawalIndex,proto3" json:"next_withdrawal_index,omitempty"`
	NextWithdrawalValidatorIndex github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex `protobuf:"varint,11002,opt,name=next_withdrawal_validator_index,json=nextWithdrawalValidatorIndex,proto3" json:"next_withdrawal_validator_index,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.ValidatorIndex"`
	HistoricalSummaries          []*HistoricalSummary                                              `protobuf:"bytes,11003,rep,name=historical_summaries,json=historicalSummaries,proto3" json:"historical_summaries,omitempty" ssz-max:"16777216"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *BeaconStateZond) Reset() {
	*x = BeaconStateZond{}
	mi := &file_proto_qrysm_v1alpha1_beacon_state_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeaconStateZond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconStateZond) ProtoMessage() {}

func (x *BeaconStateZond) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_state_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconStateZond.ProtoReflect.Descriptor instead.
func (*BeaconStateZond) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_state_proto_rawDescGZIP(), []int{10}
}

func (x *BeaconStateZond) GetGenesisTime() uint64 {
	if x != nil {
		return x.GenesisTime
	}
	return 0
}

func (x *BeaconStateZond) GetGenesisValidatorsRoot() []byte {
	if x != nil {
		return x.GenesisValidatorsRoot
	}
	return nil
}

func (x *BeaconStateZond) GetSlot() github_com_theQRL_qrysm_consensus_types_primitives.Slot {
	if x != nil {
		return x.Slot
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Slot(0)
}

func (x *BeaconStateZond) GetFork() *Fork {
	if x != nil {
		return x.Fork
	}
	return nil
}

func (x *BeaconStateZond) GetLatestBlockHeader() *BeaconBlockHeader {
	if x != nil {
		return x.LatestBlockHeader
	}
	return nil
}

func (x *BeaconStateZond) GetBlockRoots() [][]byte {
	if x != nil {
		return x.BlockRoots
	}
	return nil
}

func (x *BeaconStateZond) GetStateRoots() [][]byte {
	if x != nil {
		return x.StateRoots
	}
	return nil
}

func (x *BeaconStateZond) GetHistoricalRoots() [][]byte {
	if x != nil {
		return x.HistoricalRoots
	}
	return nil
}

func (x *BeaconStateZond) GetExecutionData() *ExecutionData {
	if x != nil {
		return x.ExecutionData
	}
	return nil
}

func (x *BeaconStateZond) GetExecutionDataVotes() []*ExecutionData {
	if x != nil {
		return x.ExecutionDataVotes
	}
	return nil
}

func (x *BeaconStateZond) GetExecutionDepositIndex() uint64 {
	if x != nil {
		return x.ExecutionDepositIndex
	}
	return 0
}

func (x *BeaconStateZond) GetValidators() []*Validator {
	if x != nil {
		return x.Validators
	}
	return nil
}

func (x *BeaconStateZond) GetBalances() []uint64 {
	if x != nil {
		return x.Balances
	}
	return nil
}

func (x *BeaconStateZond) GetRandaoMixes() [][]byte {
	if x != nil {
		return x.RandaoMixes
	}
	return nil
}

func (x *BeaconStateZond) GetSlashings() []uint64 {
	if x != nil {
		return x.Slashings
	}
	return nil
}

func (x *BeaconStateZond) GetPreviousEpochParticipation() []byte {
	if x != nil {
		return x.PreviousEpochParticipation
	}
	return nil
}

func (x *BeaconStateZond) GetCurrentEpochParticipation() []byte {
	if x != nil {
		return x.CurrentEpochParticipation
	}
	return nil
}

func (x *BeaconStateZond) GetJustificationBits() github_com_theQRL_go_bitfield.Bitvector4 {
	if x != nil {
		return x.JustificationBits
	}
	return github_com_theQRL_go_bitfield.Bitvector4(nil)
}

func (x *BeaconStateZond) GetPreviousJustifiedCheckpoint() *Checkpoint {
	if x != nil {
		return x.PreviousJustifiedCheckpoint
	}
	return nil
}

func (x *BeaconStateZond) GetCurrentJustifiedCheckpoint() *Checkpoint {
	if x != nil {
		return x.CurrentJustifiedCheckpoint
	}
	return nil
}

func (x *BeaconStateZond) GetFinalizedCheckpoint() *Checkpoint {
	if x != nil {
		return x.FinalizedCheckpoint
	}
	return nil
}

func (x *BeaconStateZond) GetInactivityScores() []uint64 {
	if x != nil {
		return x.InactivityScores
	}
	return nil
}

func (x *BeaconStateZond) GetCurrentSyncCommittee() *SyncCommittee {
	if x != nil {
		return x.CurrentSyncCommittee
	}
	return nil
}

func (x *BeaconStateZond) GetNextSyncCommittee() *SyncCommittee {
	if x != nil {
		return x.NextSyncCommittee
	}
	return nil
}

func (x *BeaconStateZond) GetLatestExecutionPayloadHeader() *v1.ExecutionPayloadHeaderZond {
	if x != nil {
		return x.LatestExecutionPayloadHeader
	}
	return nil
}

func (x *BeaconStateZond) GetNextWithdrawalIndex() uint64 {
	if x != nil {
		return x.NextWithdrawalIndex
	}
	return 0
}

func (x *BeaconStateZond) GetNextWithdrawalValidatorIndex() github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex {
	if x != nil {
		return x.NextWithdrawalValidatorIndex
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex(0)
}

func (x *BeaconStateZond) GetHistoricalSummaries() []*HistoricalSummary {
	if x != nil {
		return x.HistoricalSummaries
	}
	return nil
}

type HistoricalSummary struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BlockSummaryRoot []byte                 `protobuf:"bytes,1,opt,name=block_summary_root,json=blockSummaryRoot,proto3" json:"block_summary_root,omitempty" ssz-size:"32"`
	StateSummaryRoot []byte                 `protobuf:"bytes,2,opt,name=state_summary_root,json=stateSummaryRoot,proto3" json:"state_summary_root,omitempty" ssz-size:"32"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HistoricalSummary) Reset() {
	*x = HistoricalSummary{}
	mi := &file_proto_qrysm_v1alpha1_beacon_state_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoricalSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoricalSummary) ProtoMessage() {}

func (x *HistoricalSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_state_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoricalSummary.ProtoReflect.Descriptor instead.
func (*HistoricalSummary) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_state_proto_rawDescGZIP(), []int{11}
}

func (x *HistoricalSummary) GetBlockSummaryRoot() []byte {
	if x != nil {
		return x.BlockSummaryRoot
	}
	return nil
}

func (x *HistoricalSummary) GetStateSummaryRoot() []byte {
	if x != nil {
		return x.StateSummaryRoot
	}
	return nil
}

var File_proto_qrysm_v1alpha1_beacon_state_proto protoreflect.FileDescriptor

const file_proto_qrysm_v1alpha1_beacon_state_proto_rawDesc = "" +
	"\n" +
	"'proto/qrysm/v1alpha1/beacon_state.proto\x12\x13theqrl.qrl.v1alpha1\x1a&proto/qrysm/v1alpha1/attestation.proto\x1a'proto/qrysm/v1alpha1/beacon_block.proto\x1a$proto/qrysm/v1alpha1/validator.proto\x1a&proto/engine/v1/execution_engine.proto\x1a\x1bproto/qrl/ext/options.proto\"\xbc\x01\n" +
	"\x04Fork\x120\n" +
	"\x10previous_version\x18\x01 \x01(\fB\x05\x8a\xb5\x18\x014R\x0fpreviousVersion\x12.\n" +
	"\x0fcurrent_version\x18\x02 \x01(\fB\x05\x8a\xb5\x18\x014R\x0ecurrentVersion\x12R\n" +
	"\x05epoch\x18\x03 \x01(\x04B<\x82\xb5\x188github.com/theQRL/qrysm/consensus-types/primitives.EpochR\x05epoch\"\xfe\x02\n" +
	"\x12PendingAttestation\x12Z\n" +
	"\x10aggregation_bits\x18\x01 \x01(\fB/\x82\xb5\x18%github.com/theQRL/go-bitfield.Bitlist\x92\xb5\x18\x0232R\x0faggregationBits\x128\n" +
	"\x04data\x18\x02 \x01(\v2$.theqrl.qrl.v1alpha1.AttestationDataR\x04data\x12d\n" +
	"\x0finclusion_delay\x18\x03 \x01(\x04B;\x82\xb5\x187github.com/theQRL/qrysm/consensus-types/primitives.SlotR\x0einclusionDelay\x12l\n" +
	"\x0eproposer_index\x18\x04 \x01(\x04BE\x82\xb5\x18Agithub.com/theQRL/qrysm/consensus-types/primitives.ValidatorIndexR\rproposerIndex\"m\n" +
	"\x0fHistoricalBatch\x12,\n" +
	"\vblock_roots\x18\x01 \x03(\fB\v\x8a\xb5\x18\a1024,32R\n" +
	"blockRoots\x12,\n" +
	"\vstate_roots\x18\x02 \x03(\fB\v\x8a\xb5\x18\a1024,32R\n" +
	"stateRoots\"s\n" +
	"\fStateSummary\x12O\n" +
	"\x04slot\x18\x01 \x01(\x04B;\x82\xb5\x187github.com/theQRL/qrysm/consensus-types/primitives.SlotR\x04slot\x12\x12\n" +
	"\x04root\x18\x02 \x01(\fR\x04root\"V\n" +
	"\vSigningData\x12'\n" +
	"\vobject_root\x18\x01 \x01(\fB\x06\x8a\xb5\x18\x0232R\n" +
	"objectRoot\x12\x1e\n" +
	"\x06domain\x18\x02 \x01(\fB\x06\x8a\xb5\x18\x0232R\x06domain\"z\n" +
	"\bForkData\x12.\n" +
	"\x0fcurrent_version\x18\x01 \x01(\fB\x05\x8a\xb5\x18\x014R\x0ecurrentVersion\x12>\n" +
	"\x17genesis_validators_root\x18\x02 \x01(\fB\x06\x8a\xb5\x18\x0232R\x15genesisValidatorsRoot\"\xb5\x01\n" +
	"\vCheckPtInfo\x12\x12\n" +
	"\x04seed\x18\x01 \x01(\fR\x04seed\x12!\n" +
	"\fgenesis_root\x18\x02 \x01(\fR\vgenesisRoot\x12%\n" +
	"\x0eactive_indices\x18\x03 \x03(\x04R\ractiveIndices\x12\x19\n" +
	"\bpub_keys\x18\x04 \x03(\fR\apubKeys\x12-\n" +
	"\x04fork\x18\x05 \x01(\v2\x19.theqrl.qrl.v1alpha1.ForkR\x04fork\"\xcb\x01\n" +
	"\x0eDepositMessage\x121\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fB\x12\x8a\xb5\x18\x042592\x9a\xb5\x18\x06pubkeyR\tpublicKey\x129\n" +
	"\x14withdrawal_recipient\x18\x02 \x01(\fB\x06\x8a\xb5\x18\x0264R\x13withdrawalRecipient\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\x123\n" +
	"\x11randao_commitment\x18\x04 \x01(\fB\x06\x8a\xb5\x18\x0232R\x10randaoCommitment\"7\n" +
	"\rSyncCommittee\x12&\n" +
	"\apubkeys\x18\x01 \x03(\fB\f\x8a\xb5\x18\b128,2592R\apubkeys\"\x9d\x01\n" +
	"\x1bSyncAggregatorSelectionData\x12O\n" +
	"\x04slot\x18\x01 \x01(\x04B;\x82\xb5\x187github.com/theQRL/qrysm/consensus-types/primitives.SlotR\x04slot\x12-\n" +
	"\x12subcommittee_index\x18\x02 \x01(\x04R\x11subcommitteeIndex\"\xf7\x10\n" +
	"\x0fBeaconStateZond\x12\"\n" +
	"\fgenesis_time\x18\xe9\a \x01(\x04R\vgenesisTime\x12?\n" +
	"\x17genesis_validators_root\x18\xea\a \x01(\fB\x06\x8a\xb5\x18\x0232R\x15genesisValidatorsRoot\x12P\n" +
	"\x04slot\x18\xeb\a \x01(\x04B;\x82\xb5\x187github.com/theQRL/qrysm/consensus-types/primitives.SlotR\x04slot\x12.\n" +
	"\x04fork\x18\xec\a \x01(\v2\x19.theqrl.qrl.v1alpha1.ForkR\x04fork\x12W\n" +
	"\x13latest_block_header\x18\xd1\x0f \x01(\v2&.theqrl.qrl.v1alpha1.BeaconBlockHeaderR\x11latestBlockHeader\x12-\n" +
	"\vblock_roots\x18\xd2\x0f \x03(\fB\v\x8a\xb5\x18\a1024,32R\n" +
	"blockRoots\x12-\n" +
	"\vstate_roots\x18\xd3\x0f \x03(\fB\v\x8a\xb5\x18\a1024,32R\n" +
	"stateRoots\x12@\n" +
	"\x10historical_roots\x18\xd4\x0f \x03(\fB\x14\x8a\xb5\x18\x04?,32\x92\xb5\x18\b16777216R\x0fhistoricalRoots\x12J\n" +
	"\x0eexecution_data\x18\xb9\x17 \x01(\v2\".theqrl.qrl.v1alpha1.ExecutionDataR\rexecutionData\x12^\n" +
	"\x14execution_data_votes\x18\xba\x17 \x03(\v2\".theqrl.qrl.v1alpha1.ExecutionDataB\a\x92\xb5\x18\x03512R\x12executionDataVotes\x127\n" +
	"\x17execution_deposit_index\x18\xbb\x17 \x01(\x04R\x15executionDepositIndex\x12R\n" +
	"\n" +
	"validators\x18\xa1\x1f \x03(\v2\x1e.theqrl.qrl.v1alpha1.ValidatorB\x11\x92\xb5\x18\r1099511627776R\n" +
	"validators\x12.\n" +
	"\bbalances\x18\xa2\x1f \x03(\x04B\x11\x92\xb5\x18\r1099511627776R\bbalances\x120\n" +
	"\frandao_mixes\x18\x89' \x03(\fB\f\x8a\xb5\x18\b65536,32R\vrandaoMixes\x12'\n" +
	"\tslashings\x18\xf1. \x03(\x04B\b\x8a\xb5\x18\x041024R\tslashings\x12T\n" +
	"\x1cprevious_epoch_participation\x18\xd96 \x01(\fB\x11\x92\xb5\x18\r1099511627776R\x1apreviousEpochParticipation\x12R\n" +
	"\x1bcurrent_epoch_participation\x18\xda6 \x01(\fB\x11\x92\xb5\x18\r1099511627776R\x19currentEpochParticipation\x12a\n" +
	"\x12justification_bits\x18\xc1> \x01(\fB1\x82\xb5\x18(github.com/theQRL/go-bitfield.Bitvector4\x8a\xb5\x18\x011R\x11justificationBits\x12d\n" +
	"\x1dprevious_justified_checkpoint\x18\xc2> \x01(\v2\x1f.theqrl.qrl.v1alpha1.CheckpointR\x1bpreviousJustifiedCheckpoint\x12b\n" +
	"\x1ccurrent_justified_checkpoint\x18\xc3> \x01(\v2\x1f.theqrl.qrl.v1alpha1.CheckpointR\x1acurrentJustifiedCheckpoint\x12S\n" +
	"\x14finalized_checkpoint\x18\xc4> \x01(\v2\x1f.theqrl.qrl.v1alpha1.CheckpointR\x13finalizedCheckpoint\x12?\n" +
	"\x11inactivity_scores\x18\xa9F \x03(\x04B\x11\x92\xb5\x18\r1099511627776R\x10inactivityScores\x12Y\n" +
	"\x16current_sync_committee\x18\xaaF \x01(\v2\".theqrl.qrl.v1alpha1.SyncCommitteeR\x14currentSyncCommittee\x12S\n" +
	"\x13next_sync_committee\x18\xabF \x01(\v2\".theqrl.qrl.v1alpha1.SyncCommitteeR\x11nextSyncCommittee\x12t\n" +
	"\x1flatest_execution_payload_header\x18\x91N \x01(\v2,.theqrl.engine.v1.ExecutionPayloadHeaderZondR\x1clatestExecutionPayloadHeader\x123\n" +
	"\x15next_withdrawal_index\x18\xf9U \x01(\x04R\x13nextWithdrawalIndex\x12\x8d\x01\n" +
	"\x1fnext_withdrawal_validator_index\x18\xfaU \x01(\x04BE\x82\xb5\x18Agithub.com/theQRL/qrysm/consensus-types/primitives.ValidatorIndexR\x1cnextWithdrawalValidatorIndex\x12h\n" +
	"\x14historical_summaries\x18\xfbU \x03(\v2&.theqrl.qrl.v1alpha1.HistoricalSummaryB\f\x92\xb5\x18\b16777216R\x13historicalSummaries\"\x7f\n" +
	"\x11HistoricalSummary\x124\n" +
	"\x12block_summary_root\x18\x01 \x01(\fB\x06\x8a\xb5\x18\x0232R\x10blockSummaryRoot\x124\n" +
	"\x12state_summary_root\x18\x02 \x01(\fB\x06\x8a\xb5\x18\x0232R\x10stateSummaryRootB\x8b\x01\n" +
	"\x17org.theqrl.qrl.v1alpha1B\x10BeaconStateProtoP\x01Z0github.com/theQRL/qrysm/proto/qrysm/v1alpha1;qrl\xaa\x02\x13TheQRL.QRL.V1Alpha1\xca\x02\x13TheQRL\\QRL\\v1alpha1b\x06proto3"

var (
	file_proto_qrysm_v1alpha1_beacon_state_proto_rawDescOnce sync.Once
	file_proto_qrysm_v1alpha1_beacon_state_proto_rawDescData []byte
)

func file_proto_qrysm_v1alpha1_beacon_state_proto_rawDescGZIP() []byte {
	file_proto_qrysm_v1alpha1_beacon_state_proto_rawDescOnce.Do(func() {
		file_proto_qrysm_v1alpha1_beacon_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_qrysm_v1alpha1_beacon_state_proto_rawDesc), len(file_proto_qrysm_v1alpha1_beacon_state_proto_rawDesc)))
	})
	return file_proto_qrysm_v1alpha1_beacon_state_proto_rawDescData
}

var file_proto_qrysm_v1alpha1_beacon_state_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_qrysm_v1alpha1_beacon_state_proto_goTypes = []any{
	(*Fork)(nil),                          // 0: theqrl.qrl.v1alpha1.Fork
	(*PendingAttestation)(nil),            // 1: theqrl.qrl.v1alpha1.PendingAttestation
	(*HistoricalBatch)(nil),               // 2: theqrl.qrl.v1alpha1.HistoricalBatch
	(*StateSummary)(nil),                  // 3: theqrl.qrl.v1alpha1.StateSummary
	(*SigningData)(nil),                   // 4: theqrl.qrl.v1alpha1.SigningData
	(*ForkData)(nil),                      // 5: theqrl.qrl.v1alpha1.ForkData
	(*CheckPtInfo)(nil),                   // 6: theqrl.qrl.v1alpha1.CheckPtInfo
	(*DepositMessage)(nil),                // 7: theqrl.qrl.v1alpha1.DepositMessage
	(*SyncCommittee)(nil),                 // 8: theqrl.qrl.v1alpha1.SyncCommittee
	(*SyncAggregatorSelectionData)(nil),   // 9: theqrl.qrl.v1alpha1.SyncAggregatorSelectionData
	(*BeaconStateZond)(nil),               // 10: theqrl.qrl.v1alpha1.BeaconStateZond
	(*HistoricalSummary)(nil),             // 11: theqrl.qrl.v1alpha1.HistoricalSummary
	(*AttestationData)(nil),               // 12: theqrl.qrl.v1alpha1.AttestationData
	(*BeaconBlockHeader)(nil),             // 13: theqrl.qrl.v1alpha1.BeaconBlockHeader
	(*ExecutionData)(nil),                 // 14: theqrl.qrl.v1alpha1.ExecutionData
	(*Validator)(nil),                     // 15: theqrl.qrl.v1alpha1.Validator
	(*Checkpoint)(nil),                    // 16: theqrl.qrl.v1alpha1.Checkpoint
	(*v1.ExecutionPayloadHeaderZond)(nil), // 17: theqrl.engine.v1.ExecutionPayloadHeaderZond
}
var file_proto_qrysm_v1alpha1_beacon_state_proto_depIdxs = []int32{
	12, // 0: theqrl.qrl.v1alpha1.PendingAttestation.data:type_name -> theqrl.qrl.v1alpha1.AttestationData
	0,  // 1: theqrl.qrl.v1alpha1.CheckPtInfo.fork:type_name -> theqrl.qrl.v1alpha1.Fork
	0,  // 2: theqrl.qrl.v1alpha1.BeaconStateZond.fork:type_name -> theqrl.qrl.v1alpha1.Fork
	13, // 3: theqrl.qrl.v1alpha1.BeaconStateZond.latest_block_header:type_name -> theqrl.qrl.v1alpha1.BeaconBlockHeader
	14, // 4: theqrl.qrl.v1alpha1.BeaconStateZond.execution_data:type_name -> theqrl.qrl.v1alpha1.ExecutionData
	14, // 5: theqrl.qrl.v1alpha1.BeaconStateZond.execution_data_votes:type_name -> theqrl.qrl.v1alpha1.ExecutionData
	15, // 6: theqrl.qrl.v1alpha1.BeaconStateZond.validators:type_name -> theqrl.qrl.v1alpha1.Validator
	16, // 7: theqrl.qrl.v1alpha1.BeaconStateZond.previous_justified_checkpoint:type_name -> theqrl.qrl.v1alpha1.Checkpoint
	16, // 8: theqrl.qrl.v1alpha1.BeaconStateZond.current_justified_checkpoint:type_name -> theqrl.qrl.v1alpha1.Checkpoint
	16, // 9: theqrl.qrl.v1alpha1.BeaconStateZond.finalized_checkpoint:type_name -> theqrl.qrl.v1alpha1.Checkpoint
	8,  // 10: theqrl.qrl.v1alpha1.BeaconStateZond.current_sync_committee:type_name -> theqrl.qrl.v1alpha1.SyncCommittee
	8,  // 11: theqrl.qrl.v1alpha1.BeaconStateZond.next_sync_committee:type_name -> theqrl.qrl.v1alpha1.SyncCommittee
	17, // 12: theqrl.qrl.v1alpha1.BeaconStateZond.latest_execution_payload_header:type_name -> theqrl.engine.v1.ExecutionPayloadHeaderZond
	11, // 13: theqrl.qrl.v1alpha1.BeaconStateZond.historical_summaries:type_name -> theqrl.qrl.v1alpha1.HistoricalSummary
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_qrysm_v1alpha1_beacon_state_proto_init() }
func file_proto_qrysm_v1alpha1_beacon_state_proto_init() {
	if File_proto_qrysm_v1alpha1_beacon_state_proto != nil {
		return
	}
	file_proto_qrysm_v1alpha1_attestation_proto_init()
	file_proto_qrysm_v1alpha1_beacon_block_proto_init()
	file_proto_qrysm_v1alpha1_validator_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_qrysm_v1alpha1_beacon_state_proto_rawDesc), len(file_proto_qrysm_v1alpha1_beacon_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_qrysm_v1alpha1_beacon_state_proto_goTypes,
		DependencyIndexes: file_proto_qrysm_v1alpha1_beacon_state_proto_depIdxs,
		MessageInfos:      file_proto_qrysm_v1alpha1_beacon_state_proto_msgTypes,
	}.Build()
	File_proto_qrysm_v1alpha1_beacon_state_proto = out.File
	file_proto_qrysm_v1alpha1_beacon_state_proto_goTypes = nil
	file_proto_qrysm_v1alpha1_beacon_state_proto_depIdxs = nil
}
