// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: proto/qrl/v1/beacon_state.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	github_com_theQRL_go_bitfield "github.com/theQRL/go-bitfield"
	github_com_theQRL_qrysm_consensus_types_primitives "github.com/theQRL/qrysm/consensus-types/primitives"
	v1 "github.com/theQRL/qrysm/proto/engine/v1"
	_ "github.com/theQRL/qrysm/proto/qrl/ext"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PendingAttestation struct {
	state           protoimpl.MessageState                                            `protogen:"open.v1"`
	AggregationBits github_com_theQRL_go_bitfield.Bitlist                             `protobuf:"bytes,1,opt,name=aggregation_bits,json=aggregationBits,proto3" json:"aggregation_bits,omitempty" cast-type:"github.com/theQRL/go-bitfield.Bitlist" ssz-max:"32"`
	Data            *AttestationData                                                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	InclusionDelay  github_com_theQRL_qrysm_consensus_types_primitives.Slot           `protobuf:"varint,3,opt,name=inclusion_delay,json=inclusionDelay,proto3" json:"inclusion_delay,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Slot"`
	ProposerIndex   github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex `protobuf:"varint,4,opt,name=proposer_index,json=proposerIndex,proto3" json:"proposer_index,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.ValidatorIndex"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PendingAttestation) Reset() {
	*x = PendingAttestation{}
	mi := &file_proto_qrl_v1_beacon_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingAttestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingAttestation) ProtoMessage() {}

func (x *PendingAttestation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_beacon_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingAttestation.ProtoReflect.Descriptor instead.
func (*PendingAttestation) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_beacon_state_proto_rawDescGZIP(), []int{0}
}

func (x *PendingAttestation) GetAggregationBits() github_com_theQRL_go_bitfield.Bitlist {
	if x != nil {
		return x.AggregationBits
	}
	return github_com_theQRL_go_bitfield.Bitlist(nil)
}

func (x *PendingAttestation) GetData() *AttestationData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PendingAttestation) GetInclusionDelay() github_com_theQRL_qrysm_consensus_types_primitives.Slot {
	if x != nil {
		return x.InclusionDelay
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Slot(0)
}

func (x *PendingAttestation) GetProposerIndex() github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex {
	if x != nil {
		return x.ProposerIndex
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex(0)
}

type Committee struct {
	state         protoimpl.MessageState                                              `protogen:"open.v1"`
	Index         github_com_theQRL_qrysm_consensus_types_primitives.CommitteeIndex   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.CommitteeIndex"`
	Slot          github_com_theQRL_qrysm_consensus_types_primitives.Slot             `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Slot"`
	Validators    []github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex `protobuf:"varint,3,rep,packed,name=validators,proto3" json:"validators,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.ValidatorIndex"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Committee) Reset() {
	*x = Committee{}
	mi := &file_proto_qrl_v1_beacon_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Committee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Committee) ProtoMessage() {}

func (x *Committee) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_beacon_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Committee.ProtoReflect.Descriptor instead.
func (*Committee) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_beacon_state_proto_rawDescGZIP(), []int{1}
}

func (x *Committee) GetIndex() github_com_theQRL_qrysm_consensus_types_primitives.CommitteeIndex {
	if x != nil {
		return x.Index
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.CommitteeIndex(0)
}

func (x *Committee) GetSlot() github_com_theQRL_qrysm_consensus_types_primitives.Slot {
	if x != nil {
		return x.Slot
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Slot(0)
}

func (x *Committee) GetValidators() []github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex {
	if x != nil {
		return x.Validators
	}
	return []github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex(nil)
}

type Fork struct {
	state           protoimpl.MessageState                                   `protogen:"open.v1"`
	PreviousVersion []byte                                                   `protobuf:"bytes,1,opt,name=previous_version,json=previousVersion,proto3" json:"previous_version,omitempty" ssz-size:"4"`
	CurrentVersion  []byte                                                   `protobuf:"bytes,2,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty" ssz-size:"4"`
	Epoch           github_com_theQRL_qrysm_consensus_types_primitives.Epoch `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Epoch"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Fork) Reset() {
	*x = Fork{}
	mi := &file_proto_qrl_v1_beacon_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fork) ProtoMessage() {}

func (x *Fork) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_beacon_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fork.ProtoReflect.Descriptor instead.
func (*Fork) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_beacon_state_proto_rawDescGZIP(), []int{2}
}

func (x *Fork) GetPreviousVersion() []byte {
	if x != nil {
		return x.PreviousVersion
	}
	return nil
}

func (x *Fork) GetCurrentVersion() []byte {
	if x != nil {
		return x.CurrentVersion
	}
	return nil
}

func (x *Fork) GetEpoch() github_com_theQRL_qrysm_consensus_types_primitives.Epoch {
	if x != nil {
		return x.Epoch
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Epoch(0)
}

type BeaconStateZond struct {
	state                        protoimpl.MessageState                                            `protogen:"open.v1"`
	GenesisTime                  uint64                                                            `protobuf:"varint,1001,opt,name=genesis_time,json=genesisTime,proto3" json:"genesis_time,omitempty"`
	GenesisValidatorsRoot        []byte                                                            `protobuf:"bytes,1002,opt,name=genesis_validators_root,json=genesisValidatorsRoot,proto3" json:"genesis_validators_root,omitempty" ssz-size:"32"`
	Slot                         github_com_theQRL_qrysm_consensus_types_primitives.Slot           `protobuf:"varint,1003,opt,name=slot,proto3" json:"slot,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Slot"`
	Fork                         *Fork                                                             `protobuf:"bytes,1004,opt,name=fork,proto3" json:"fork,omitempty"`
	LatestBlockHeader            *BeaconBlockHeader                                                `protobuf:"bytes,2001,opt,name=latest_block_header,json=latestBlockHeader,proto3" json:"latest_block_header,omitempty"`
	BlockRoots                   [][]byte                                                          `protobuf:"bytes,2002,rep,name=block_roots,json=blockRoots,proto3" json:"block_roots,omitempty" ssz-size:"1024,32"`
	StateRoots                   [][]byte                                                          `protobuf:"bytes,2003,rep,name=state_roots,json=stateRoots,proto3" json:"state_roots,omitempty" ssz-size:"1024,32"`
	HistoricalRoots              [][]byte                                                          `protobuf:"bytes,2004,rep,name=historical_roots,json=historicalRoots,proto3" json:"historical_roots,omitempty" ssz-max:"16777216" ssz-size:"?,32"`
	ExecutionData                *ExecutionData                                                    `protobuf:"bytes,3001,opt,name=execution_data,json=executionData,proto3" json:"execution_data,omitempty"`
	ExecutionDataVotes           []*ExecutionData                                                  `protobuf:"bytes,3002,rep,name=execution_data_votes,json=executionDataVotes,proto3" json:"execution_data_votes,omitempty" ssz-max:"512"`
	ExecutionDepositIndex        uint64                                                            `protobuf:"varint,3003,opt,name=execution_deposit_index,json=executionDepositIndex,proto3" json:"execution_deposit_index,omitempty"`
	Validators                   []*Validator                                                      `protobuf:"bytes,4001,rep,name=validators,proto3" json:"validators,omitempty" ssz-max:"1099511627776"`
	Balances                     []uint64                                                          `protobuf:"varint,4002,rep,packed,name=balances,proto3" json:"balances,omitempty" ssz-max:"1099511627776"`
	RandaoMixes                  [][]byte                                                          `protobuf:"bytes,5001,rep,name=randao_mixes,json=randaoMixes,proto3" json:"randao_mixes,omitempty" ssz-size:"65536,32"`
	Slashings                    []uint64                                                          `protobuf:"varint,6001,rep,packed,name=slashings,proto3" json:"slashings,omitempty" ssz-size:"1024"`
	PreviousEpochParticipation   []byte                                                            `protobuf:"bytes,7001,opt,name=previous_epoch_participation,json=previousEpochParticipation,proto3" json:"previous_epoch_participation,omitempty" ssz-max:"1099511627776"`
	CurrentEpochParticipation    []byte                                                            `protobuf:"bytes,7002,opt,name=current_epoch_participation,json=currentEpochParticipation,proto3" json:"current_epoch_participation,omitempty" ssz-max:"1099511627776"`
	JustificationBits            github_com_theQRL_go_bitfield.Bitvector4                          `protobuf:"bytes,8001,opt,name=justification_bits,json=justificationBits,proto3" json:"justification_bits,omitempty" cast-type:"github.com/theQRL/go-bitfield.Bitvector4" ssz-size:"1"`
	PreviousJustifiedCheckpoint  *Checkpoint                                                       `protobuf:"bytes,8002,opt,name=previous_justified_checkpoint,json=previousJustifiedCheckpoint,proto3" json:"previous_justified_checkpoint,omitempty"`
	CurrentJustifiedCheckpoint   *Checkpoint                                                       `protobuf:"bytes,8003,opt,name=current_justified_checkpoint,json=currentJustifiedCheckpoint,proto3" json:"current_justified_checkpoint,omitempty"`
	FinalizedCheckpoint          *Checkpoint                                                       `protobuf:"bytes,8004,opt,name=finalized_checkpoint,json=finalizedCheckpoint,proto3" json:"finalized_checkpoint,omitempty"`
	InactivityScores             []uint64                                                          `protobuf:"varint,9001,rep,packed,name=inactivity_scores,json=inactivityScores,proto3" json:"inactivity_scores,omitempty" ssz-max:"1099511627776"`
	CurrentSyncCommittee         *SyncCommittee                                                    `protobuf:"bytes,9002,opt,name=current_sync_committee,json=currentSyncCommittee,proto3" json:"current_sync_committee,omitempty"`
	NextSyncCommittee            *SyncCommittee                                                    `protobuf:"bytes,9003,opt,name=next_sync_committee,json=nextSyncCommittee,proto3" json:"next_sync_committee,omitempty"`
	LatestExecutionPayloadHeader *v1.ExecutionPayloadHeaderZond                                    `protobuf:"bytes,10001,opt,name=latest_execution_payload_header,json=latestExecutionPayloadHeader,proto3" json:"latest_execution_payload_header,omitempty"`
	NextWithdrawalIndex          uint64                                                            `protobuf:"varint,11001,opt,name=next_withdrawal_index,json=nextWithdrawalIndex,proto3" json:"next_withdrawal_index,omitempty"`
	NextWithdrawalValidatorIndex github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex `protobuf:"varint,11002,opt,name=next_withdrawal_validator_index,json=nextWithdrawalValidatorIndex,proto3" json:"next_withdrawal_validator_index,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.ValidatorIndex"`
	HistoricalSummaries          []*HistoricalSummary                                              `protobuf:"bytes,11003,rep,name=historical_summaries,json=historicalSummaries,proto3" json:"historical_summaries,omitempty" ssz-max:"16777216"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *BeaconStateZond) Reset() {
	*x = BeaconStateZond{}
	mi := &file_proto_qrl_v1_beacon_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeaconStateZond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconStateZond) ProtoMessage() {}

func (x *BeaconStateZond) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_beacon_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconStateZond.ProtoReflect.Descriptor instead.
func (*BeaconStateZond) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_beacon_state_proto_rawDescGZIP(), []int{3}
}

func (x *BeaconStateZond) GetGenesisTime() uint64 {
	if x != nil {
		return x.GenesisTime
	}
	return 0
}

func (x *BeaconStateZond) GetGenesisValidatorsRoot() []byte {
	if x != nil {
		return x.GenesisValidatorsRoot
	}
	return nil
}

func (x *BeaconStateZond) GetSlot() github_com_theQRL_qrysm_consensus_types_primitives.Slot {
	if x != nil {
		return x.Slot
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Slot(0)
}

func (x *BeaconStateZond) GetFork() *Fork {
	if x != nil {
		return x.Fork
	}
	return nil
}

func (x *BeaconStateZond) GetLatestBlockHeader() *BeaconBlockHeader {
	if x != nil {
		return x.LatestBlockHeader
	}
	return nil
}

func (x *BeaconStateZond) GetBlockRoots() [][]byte {
	if x != nil {
		return x.BlockRoots
	}
	return nil
}

func (x *BeaconStateZond) GetStateRoots() [][]byte {
	if x != nil {
		return x.StateRoots
	}
	return nil
}

func (x *BeaconStateZond) GetHistoricalRoots() [][]byte {
	if x != nil {
		return x.HistoricalRoots
	}
	return nil
}

func (x *BeaconStateZond) GetExecutionData() *ExecutionData {
	if x != nil {
		return x.ExecutionData
	}
	return nil
}

func (x *BeaconStateZond) GetExecutionDataVotes() []*ExecutionData {
	if x != nil {
		return x.ExecutionDataVotes
	}
	return nil
}

func (x *BeaconStateZond) GetExecutionDepositIndex() uint64 {
	if x != nil {
		return x.ExecutionDepositIndex
	}
	return 0
}

func (x *BeaconStateZond) GetValidators() []*Validator {
	if x != nil {
		return x.Validators
	}
	return nil
}

func (x *BeaconStateZond) GetBalances() []uint64 {
	if x != nil {
		return x.Balances
	}
	return nil
}

func (x *BeaconStateZond) GetRandaoMixes() [][]byte {
	if x != nil {
		return x.RandaoMixes
	}
	return nil
}

func (x *BeaconStateZond) GetSlashings() []uint64 {
	if x != nil {
		return x.Slashings
	}
	return nil
}

func (x *BeaconStateZond) GetPreviousEpochParticipation() []byte {
	if x != nil {
		return x.PreviousEpochParticipation
	}
	return nil
}

func (x *BeaconStateZond) GetCurrentEpochParticipation() []byte {
	if x != nil {
		return x.CurrentEpochParticipation
	}
	return nil
}

func (x *BeaconStateZond) GetJustificationBits() github_com_theQRL_go_bitfield.Bitvector4 {
	if x != nil {
		return x.JustificationBits
	}
	return github_com_theQRL_go_bitfield.Bitvector4(nil)
}

func (x *BeaconStateZond) GetPreviousJustifiedCheckpoint() *Checkpoint {
	if x != nil {
		return x.PreviousJustifiedCheckpoint
	}
	return nil
}

func (x *BeaconStateZond) GetCurrentJustifiedCheckpoint() *Checkpoint {
	if x != nil {
		return x.CurrentJustifiedCheckpoint
	}
	return nil
}

func (x *BeaconStateZond) GetFinalizedCheckpoint() *Checkpoint {
	if x != nil {
		return x.FinalizedCheckpoint
	}
	return nil
}

func (x *BeaconStateZond) GetInactivityScores() []uint64 {
	if x != nil {
		return x.InactivityScores
	}
	return nil
}

func (x *BeaconStateZond) GetCurrentSyncCommittee() *SyncCommittee {
	if x != nil {
		return x.CurrentSyncCommittee
	}
	return nil
}

func (x *BeaconStateZond) GetNextSyncCommittee() *SyncCommittee {
	if x != nil {
		return x.NextSyncCommittee
	}
	return nil
}

func (x *BeaconStateZond) GetLatestExecutionPayloadHeader() *v1.ExecutionPayloadHeaderZond {
	if x != nil {
		return x.LatestExecutionPayloadHeader
	}
	return nil
}

func (x *BeaconStateZond) GetNextWithdrawalIndex() uint64 {
	if x != nil {
		return x.NextWithdrawalIndex
	}
	return 0
}

func (x *BeaconStateZond) GetNextWithdrawalValidatorIndex() github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex {
	if x != nil {
		return x.NextWithdrawalValidatorIndex
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex(0)
}

func (x *BeaconStateZond) GetHistoricalSummaries() []*HistoricalSummary {
	if x != nil {
		return x.HistoricalSummaries
	}
	return nil
}

type HistoricalSummary struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BlockSummaryRoot []byte                 `protobuf:"bytes,1,opt,name=block_summary_root,json=blockSummaryRoot,proto3" json:"block_summary_root,omitempty" ssz-size:"32"`
	StateSummaryRoot []byte                 `protobuf:"bytes,2,opt,name=state_summary_root,json=stateSummaryRoot,proto3" json:"state_summary_root,omitempty" ssz-size:"32"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HistoricalSummary) Reset() {
	*x = HistoricalSummary{}
	mi := &file_proto_qrl_v1_beacon_state_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoricalSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoricalSummary) ProtoMessage() {}

func (x *HistoricalSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_beacon_state_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoricalSummary.ProtoReflect.Descriptor instead.
func (*HistoricalSummary) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_beacon_state_proto_rawDescGZIP(), []int{4}
}

func (x *HistoricalSummary) GetBlockSummaryRoot() []byte {
	if x != nil {
		return x.BlockSummaryRoot
	}
	return nil
}

func (x *HistoricalSummary) GetStateSummaryRoot() []byte {
	if x != nil {
		return x.StateSummaryRoot
	}
	return nil
}

type BeaconStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StateId       []byte                 `protobuf:"bytes,1,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeaconStateRequest) Reset() {
	*x = BeaconStateRequest{}
	mi := &file_proto_qrl_v1_beacon_state_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeaconStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconStateRequest) ProtoMessage() {}

func (x *BeaconStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_beacon_state_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconStateRequest.ProtoReflect.Descriptor instead.
func (*BeaconStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_beacon_state_proto_rawDescGZIP(), []int{5}
}

func (x *BeaconStateRequest) GetStateId() []byte {
	if x != nil {
		return x.StateId
	}
	return nil
}

type BeaconStateResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Version             Version                `protobuf:"varint,1,opt,name=version,proto3,enum=theqrl.qrl.v1.Version" json:"version,omitempty"`
	Data                *BeaconStateContainer  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	ExecutionOptimistic bool                   `protobuf:"varint,3,opt,name=execution_optimistic,json=executionOptimistic,proto3" json:"execution_optimistic,omitempty"`
	Finalized           bool                   `protobuf:"varint,4,opt,name=finalized,proto3" json:"finalized,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BeaconStateResponse) Reset() {
	*x = BeaconStateResponse{}
	mi := &file_proto_qrl_v1_beacon_state_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeaconStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconStateResponse) ProtoMessage() {}

func (x *BeaconStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_beacon_state_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconStateResponse.ProtoReflect.Descriptor instead.
func (*BeaconStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_beacon_state_proto_rawDescGZIP(), []int{6}
}

func (x *BeaconStateResponse) GetVersion() Version {
	if x != nil {
		return x.Version
	}
	return Version_ZOND
}

func (x *BeaconStateResponse) GetData() *BeaconStateContainer {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BeaconStateResponse) GetExecutionOptimistic() bool {
	if x != nil {
		return x.ExecutionOptimistic
	}
	return false
}

func (x *BeaconStateResponse) GetFinalized() bool {
	if x != nil {
		return x.Finalized
	}
	return false
}

type BeaconStateContainer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to State:
	//
	//	*BeaconStateContainer_ZondState
	State         isBeaconStateContainer_State `protobuf_oneof:"state"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeaconStateContainer) Reset() {
	*x = BeaconStateContainer{}
	mi := &file_proto_qrl_v1_beacon_state_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeaconStateContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconStateContainer) ProtoMessage() {}

func (x *BeaconStateContainer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_beacon_state_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconStateContainer.ProtoReflect.Descriptor instead.
func (*BeaconStateContainer) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_beacon_state_proto_rawDescGZIP(), []int{7}
}

func (x *BeaconStateContainer) GetState() isBeaconStateContainer_State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *BeaconStateContainer) GetZondState() *BeaconStateZond {
	if x != nil {
		if x, ok := x.State.(*BeaconStateContainer_ZondState); ok {
			return x.ZondState
		}
	}
	return nil
}

type isBeaconStateContainer_State interface {
	isBeaconStateContainer_State()
}

type BeaconStateContainer_ZondState struct {
	ZondState *BeaconStateZond `protobuf:"bytes,1,opt,name=zond_state,json=zondState,proto3,oneof"`
}

func (*BeaconStateContainer_ZondState) isBeaconStateContainer_State() {}

type ForkChoiceHeadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*ForkChoiceHead      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForkChoiceHeadsResponse) Reset() {
	*x = ForkChoiceHeadsResponse{}
	mi := &file_proto_qrl_v1_beacon_state_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkChoiceHeadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkChoiceHeadsResponse) ProtoMessage() {}

func (x *ForkChoiceHeadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_beacon_state_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkChoiceHeadsResponse.ProtoReflect.Descriptor instead.
func (*ForkChoiceHeadsResponse) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_beacon_state_proto_rawDescGZIP(), []int{8}
}

func (x *ForkChoiceHeadsResponse) GetData() []*ForkChoiceHead {
	if x != nil {
		return x.Data
	}
	return nil
}

type ForkChoiceHead struct {
	state               protoimpl.MessageState                                  `protogen:"open.v1"`
	Root                []byte                                                  `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty" ssz-size:"32"`
	Slot                github_com_theQRL_qrysm_consensus_types_primitives.Slot `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Slot"`
	ExecutionOptimistic bool                                                    `protobuf:"varint,3,opt,name=execution_optimistic,json=executionOptimistic,proto3" json:"execution_optimistic,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ForkChoiceHead) Reset() {
	*x = ForkChoiceHead{}
	mi := &file_proto_qrl_v1_beacon_state_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkChoiceHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkChoiceHead) ProtoMessage() {}

func (x *ForkChoiceHead) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_beacon_state_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkChoiceHead.ProtoReflect.Descriptor instead.
func (*ForkChoiceHead) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_beacon_state_proto_rawDescGZIP(), []int{9}
}

func (x *ForkChoiceHead) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *ForkChoiceHead) GetSlot() github_com_theQRL_qrysm_consensus_types_primitives.Slot {
	if x != nil {
		return x.Slot
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Slot(0)
}

func (x *ForkChoiceHead) GetExecutionOptimistic() bool {
	if x != nil {
		return x.ExecutionOptimistic
	}
	return false
}

type RandaoRequest struct {
	state         protoimpl.MessageState                                    `protogen:"open.v1"`
	StateId       []byte                                                    `protobuf:"bytes,1,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	Epoch         *github_com_theQRL_qrysm_consensus_types_primitives.Epoch `protobuf:"varint,2,opt,name=epoch,proto3,oneof" json:"epoch,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Epoch"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RandaoRequest) Reset() {
	*x = RandaoRequest{}
	mi := &file_proto_qrl_v1_beacon_state_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandaoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandaoRequest) ProtoMessage() {}

func (x *RandaoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_beacon_state_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandaoRequest.ProtoReflect.Descriptor instead.
func (*RandaoRequest) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_beacon_state_proto_rawDescGZIP(), []int{10}
}

func (x *RandaoRequest) GetStateId() []byte {
	if x != nil {
		return x.StateId
	}
	return nil
}

func (x *RandaoRequest) GetEpoch() github_com_theQRL_qrysm_consensus_types_primitives.Epoch {
	if x != nil && x.Epoch != nil {
		return *x.Epoch
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Epoch(0)
}

type RandaoResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Data                *RandaoResponse_Randao `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	ExecutionOptimistic bool                   `protobuf:"varint,2,opt,name=execution_optimistic,json=executionOptimistic,proto3" json:"execution_optimistic,omitempty"`
	Finalized           bool                   `protobuf:"varint,3,opt,name=finalized,proto3" json:"finalized,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RandaoResponse) Reset() {
	*x = RandaoResponse{}
	mi := &file_proto_qrl_v1_beacon_state_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandaoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandaoResponse) ProtoMessage() {}

func (x *RandaoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_beacon_state_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandaoResponse.ProtoReflect.Descriptor instead.
func (*RandaoResponse) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_beacon_state_proto_rawDescGZIP(), []int{11}
}

func (x *RandaoResponse) GetData() *RandaoResponse_Randao {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RandaoResponse) GetExecutionOptimistic() bool {
	if x != nil {
		return x.ExecutionOptimistic
	}
	return false
}

func (x *RandaoResponse) GetFinalized() bool {
	if x != nil {
		return x.Finalized
	}
	return false
}

type RandaoResponse_Randao struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Randao        []byte                 `protobuf:"bytes,1,opt,name=randao,proto3" json:"randao,omitempty" ssz-size:"32"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RandaoResponse_Randao) Reset() {
	*x = RandaoResponse_Randao{}
	mi := &file_proto_qrl_v1_beacon_state_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandaoResponse_Randao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandaoResponse_Randao) ProtoMessage() {}

func (x *RandaoResponse_Randao) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_beacon_state_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandaoResponse_Randao.ProtoReflect.Descriptor instead.
func (*RandaoResponse_Randao) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_beacon_state_proto_rawDescGZIP(), []int{11, 0}
}

func (x *RandaoResponse_Randao) GetRandao() []byte {
	if x != nil {
		return x.Randao
	}
	return nil
}

var File_proto_qrl_v1_beacon_state_proto protoreflect.FileDescriptor

const file_proto_qrl_v1_beacon_state_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/qrl/v1/beacon_state.proto\x12\rtheqrl.qrl.v1\x1a google/protobuf/descriptor.proto\x1a\x1bproto/qrl/ext/options.proto\x1a\x1eproto/qrl/v1/attestation.proto\x1a\x1fproto/qrl/v1/beacon_block.proto\x1a\x1cproto/qrl/v1/validator.proto\x1a!proto/qrl/v1/sync_committee.proto\x1a\x1aproto/qrl/v1/version.proto\x1a&proto/engine/v1/execution_engine.proto\"\xf8\x02\n" +
	"\x12PendingAttestation\x12Z\n" +
	"\x10aggregation_bits\x18\x01 \x01(\fB/\x82\xb5\x18%github.com/theQRL/go-bitfield.Bitlist\x92\xb5\x18\x0232R\x0faggregationBits\x122\n" +
	"\x04data\x18\x02 \x01(\v2\x1e.theqrl.qrl.v1.AttestationDataR\x04data\x12d\n" +
	"\x0finclusion_delay\x18\x03 \x01(\x04B;\x82\xb5\x187github.com/theQRL/qrysm/consensus-types/primitives.SlotR\x0einclusionDelay\x12l\n" +
	"\x0eproposer_index\x18\x04 \x01(\x04BE\x82\xb5\x18Agithub.com/theQRL/qrysm/consensus-types/primitives.ValidatorIndexR\rproposerIndex\"\xa0\x02\n" +
	"\tCommittee\x12[\n" +
	"\x05index\x18\x01 \x01(\x04BE\x82\xb5\x18Agithub.com/theQRL/qrysm/consensus-types/primitives.CommitteeIndexR\x05index\x12O\n" +
	"\x04slot\x18\x02 \x01(\x04B;\x82\xb5\x187github.com/theQRL/qrysm/consensus-types/primitives.SlotR\x04slot\x12e\n" +
	"\n" +
	"validators\x18\x03 \x03(\x04BE\x82\xb5\x18Agithub.com/theQRL/qrysm/consensus-types/primitives.ValidatorIndexR\n" +
	"validators\"\xbc\x01\n" +
	"\x04Fork\x120\n" +
	"\x10previous_version\x18\x01 \x01(\fB\x05\x8a\xb5\x18\x014R\x0fpreviousVersion\x12.\n" +
	"\x0fcurrent_version\x18\x02 \x01(\fB\x05\x8a\xb5\x18\x014R\x0ecurrentVersion\x12R\n" +
	"\x05epoch\x18\x03 \x01(\x04B<\x82\xb5\x188github.com/theQRL/qrysm/consensus-types/primitives.EpochR\x05epoch\"\xb5\x10\n" +
	"\x0fBeaconStateZond\x12\"\n" +
	"\fgenesis_time\x18\xe9\a \x01(\x04R\vgenesisTime\x12?\n" +
	"\x17genesis_validators_root\x18\xea\a \x01(\fB\x06\x8a\xb5\x18\x0232R\x15genesisValidatorsRoot\x12P\n" +
	"\x04slot\x18\xeb\a \x01(\x04B;\x82\xb5\x187github.com/theQRL/qrysm/consensus-types/primitives.SlotR\x04slot\x12(\n" +
	"\x04fork\x18\xec\a \x01(\v2\x13.theqrl.qrl.v1.ForkR\x04fork\x12Q\n" +
	"\x13latest_block_header\x18\xd1\x0f \x01(\v2 .theqrl.qrl.v1.BeaconBlockHeaderR\x11latestBlockHeader\x12-\n" +
	"\vblock_roots\x18\xd2\x0f \x03(\fB\v\x8a\xb5\x18\a1024,32R\n" +
	"blockRoots\x12-\n" +
	"\vstate_roots\x18\xd3\x0f \x03(\fB\v\x8a\xb5\x18\a1024,32R\n" +
	"stateRoots\x12@\n" +
	"\x10historical_roots\x18\xd4\x0f \x03(\fB\x14\x8a\xb5\x18\x04?,32\x92\xb5\x18\b16777216R\x0fhistoricalRoots\x12D\n" +
	"\x0eexecution_data\x18\xb9\x17 \x01(\v2\x1c.theqrl.qrl.v1.ExecutionDataR\rexecutionData\x12X\n" +
	"\x14execution_data_votes\x18\xba\x17 \x03(\v2\x1c.theqrl.qrl.v1.ExecutionDataB\a\x92\xb5\x18\x03512R\x12executionDataVotes\x127\n" +
	"\x17execution_deposit_index\x18\xbb\x17 \x01(\x04R\x15executionDepositIndex\x12L\n" +
	"\n" +
	"validators\x18\xa1\x1f \x03(\v2\x18.theqrl.qrl.v1.ValidatorB\x11\x92\xb5\x18\r1099511627776R\n" +
	"validators\x12.\n" +
	"\bbalances\x18\xa2\x1f \x03(\x04B\x11\x92\xb5\x18\r1099511627776R\bbalances\x120\n" +
	"\frandao_mixes\x18\x89' \x03(\fB\f\x8a\xb5\x18\b65536,32R\vrandaoMixes\x12'\n" +
	"\tslashings\x18\xf1. \x03(\x04B\b\x8a\xb5\x18\x041024R\tslashings\x12T\n" +
	"\x1cprevious_epoch_participation\x18\xd96 \x01(\fB\x11\x92\xb5\x18\r1099511627776R\x1apreviousEpochParticipation\x12R\n" +
	"\x1bcurrent_epoch_participation\x18\xda6 \x01(\fB\x11\x92\xb5\x18\r1099511627776R\x19currentEpochParticipation\x12a\n" +
	"\x12justification_bits\x18\xc1> \x01(\fB1\x82\xb5\x18(github.com/theQRL/go-bitfield.Bitvector4\x8a\xb5\x18\x011R\x11justificationBits\x12^\n" +
	"\x1dprevious_justified_checkpoint\x18\xc2> \x01(\v2\x19.theqrl.qrl.v1.CheckpointR\x1bpreviousJustifiedCheckpoint\x12\\\n" +
	"\x1ccurrent_justified_checkpoint\x18\xc3> \x01(\v2\x19.theqrl.qrl.v1.CheckpointR\x1acurrentJustifiedCheckpoint\x12M\n" +
	"\x14finalized_checkpoint\x18\xc4> \x01(\v2\x19.theqrl.qrl.v1.CheckpointR\x13finalizedCheckpoint\x12?\n" +
	"\x11inactivity_scores\x18\xa9F \x03(\x04B\x11\x92\xb5\x18\r1099511627776R\x10inactivityScores\x12S\n" +
	"\x16current_sync_committee\x18\xaaF \x01(\v2\x1c.theqrl.qrl.v1.SyncCommitteeR\x14currentSyncCommittee\x12M\n" +
	"\x13next_sync_committee\x18\xabF \x01(\v2\x1c.theqrl.qrl.v1.SyncCommitteeR\x11nextSyncCommittee\x12t\n" +
	"\x1flatest_execution_payload_header\x18\x91N \x01(\v2,.theqrl.engine.v1.ExecutionPayloadHeaderZondR\x1clatestExecutionPayloadHeader\x123\n" +
	"\x15next_withdrawal_index\x18\xf9U \x01(\x04R\x13nextWithdrawalIndex\x12\x8d\x01\n" +
	"\x1fnext_withdrawal_validator_index\x18\xfaU \x01(\x04BE\x82\xb5\x18Agithub.com/theQRL/qrysm/consensus-types/primitives.ValidatorIndexR\x1cnextWithdrawalValidatorIndex\x12b\n" +
	"\x14historical_summaries\x18\xfbU \x03(\v2 .theqrl.qrl.v1.HistoricalSummaryB\f\x92\xb5\x18\b16777216R\x13historicalSummaries\"\x7f\n" +
	"\x11HistoricalSummary\x124\n" +
	"\x12block_summary_root\x18\x01 \x01(\fB\x06\x8a\xb5\x18\x0232R\x10blockSummaryRoot\x124\n" +
	"\x12state_summary_root\x18\x02 \x01(\fB\x06\x8a\xb5\x18\x0232R\x10stateSummaryRoot\"/\n" +
	"\x12BeaconStateRequest\x12\x19\n" +
	"\bstate_id\x18\x01 \x01(\fR\astateId\"\xd1\x01\n" +
	"\x13BeaconStateResponse\x120\n" +
	"\aversion\x18\x01 \x01(\x0e2\x16.theqrl.qrl.v1.VersionR\aversion\x127\n" +
	"\x04data\x18\x02 \x01(\v2#.theqrl.qrl.v1.BeaconStateContainerR\x04data\x121\n" +
	"\x14execution_optimistic\x18\x03 \x01(\bR\x13executionOptimistic\x12\x1c\n" +
	"\tfinalized\x18\x04 \x01(\bR\tfinalized\"`\n" +
	"\x14BeaconStateContainer\x12?\n" +
	"\n" +
	"zond_state\x18\x01 \x01(\v2\x1e.theqrl.qrl.v1.BeaconStateZondH\x00R\tzondStateB\a\n" +
	"\x05state\"L\n" +
	"\x17ForkChoiceHeadsResponse\x121\n" +
	"\x04data\x18\x01 \x03(\v2\x1d.theqrl.qrl.v1.ForkChoiceHeadR\x04data\"\xb0\x01\n" +
	"\x0eForkChoiceHead\x12\x1a\n" +
	"\x04root\x18\x01 \x01(\fB\x06\x8a\xb5\x18\x0232R\x04root\x12O\n" +
	"\x04slot\x18\x02 \x01(\x04B;\x82\xb5\x187github.com/theQRL/qrysm/consensus-types/primitives.SlotR\x04slot\x121\n" +
	"\x14execution_optimistic\x18\x03 \x01(\bR\x13executionOptimistic\"\x8d\x01\n" +
	"\rRandaoRequest\x12\x19\n" +
	"\bstate_id\x18\x01 \x01(\fR\astateId\x12W\n" +
	"\x05epoch\x18\x02 \x01(\x04B<\x82\xb5\x188github.com/theQRL/qrysm/consensus-types/primitives.EpochH\x00R\x05epoch\x88\x01\x01B\b\n" +
	"\x06_epoch\"\xc5\x01\n" +
	"\x0eRandaoResponse\x128\n" +
	"\x04data\x18\x01 \x01(\v2$.theqrl.qrl.v1.RandaoResponse.RandaoR\x04data\x121\n" +
	"\x14execution_optimistic\x18\x02 \x01(\bR\x13executionOptimistic\x12\x1c\n" +
	"\tfinalized\x18\x03 \x01(\bR\tfinalized\x1a(\n" +
	"\x06Randao\x12\x1e\n" +
	"\x06randao\x18\x01 \x01(\fB\x06\x8a\xb5\x18\x0232R\x06randaoBm\n" +
	"\x11org.theqrl.qrl.v1B\x10BeaconStateProtoP\x01Z$github.com/theQRL/qrysm/proto/qrl/v1\xaa\x02\rTheQRL.QRL.V1\xca\x02\rTheQRL\\QRL\\v1b\x06proto3"

var (
	file_proto_qrl_v1_beacon_state_proto_rawDescOnce sync.Once
	file_proto_qrl_v1_beacon_state_proto_rawDescData []byte
)

func file_proto_qrl_v1_beacon_state_proto_rawDescGZIP() []byte {
	file_proto_qrl_v1_beacon_state_proto_rawDescOnce.Do(func() {
		file_proto_qrl_v1_beacon_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_qrl_v1_beacon_state_proto_rawDesc), len(file_proto_qrl_v1_beacon_state_proto_rawDesc)))
	})
	return file_proto_qrl_v1_beacon_state_proto_rawDescData
}

var file_proto_qrl_v1_beacon_state_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_qrl_v1_beacon_state_proto_goTypes = []any{
	(*PendingAttestation)(nil),            // 0: theqrl.qrl.v1.PendingAttestation
	(*Committee)(nil),                     // 1: theqrl.qrl.v1.Committee
	(*Fork)(nil),                          // 2: theqrl.qrl.v1.Fork
	(*BeaconStateZond)(nil),               // 3: theqrl.qrl.v1.BeaconStateZond
	(*HistoricalSummary)(nil),             // 4: theqrl.qrl.v1.HistoricalSummary
	(*BeaconStateRequest)(nil),            // 5: theqrl.qrl.v1.BeaconStateRequest
	(*BeaconStateResponse)(nil),           // 6: theqrl.qrl.v1.BeaconStateResponse
	(*BeaconStateContainer)(nil),          // 7: theqrl.qrl.v1.BeaconStateContainer
	(*ForkChoiceHeadsResponse)(nil),       // 8: theqrl.qrl.v1.ForkChoiceHeadsResponse
	(*ForkChoiceHead)(nil),                // 9: theqrl.qrl.v1.ForkChoiceHead
	(*RandaoRequest)(nil),                 // 10: theqrl.qrl.v1.RandaoRequest
	(*RandaoResponse)(nil),                // 11: theqrl.qrl.v1.RandaoResponse
	(*RandaoResponse_Randao)(nil),         // 12: theqrl.qrl.v1.RandaoResponse.Randao
	(*AttestationData)(nil),               // 13: theqrl.qrl.v1.AttestationData
	(*BeaconBlockHeader)(nil),             // 14: theqrl.qrl.v1.BeaconBlockHeader
	(*ExecutionData)(nil),                 // 15: theqrl.qrl.v1.ExecutionData
	(*Validator)(nil),                     // 16: theqrl.qrl.v1.Validator
	(*Checkpoint)(nil),                    // 17: theqrl.qrl.v1.Checkpoint
	(*SyncCommittee)(nil),                 // 18: theqrl.qrl.v1.SyncCommittee
	(*v1.ExecutionPayloadHeaderZond)(nil), // 19: theqrl.engine.v1.ExecutionPayloadHeaderZond
	(Version)(0),                          // 20: theqrl.qrl.v1.Version
}
var file_proto_qrl_v1_beacon_state_proto_depIdxs = []int32{
	13, // 0: theqrl.qrl.v1.PendingAttestation.data:type_name -> theqrl.qrl.v1.AttestationData
	2,  // 1: theqrl.qrl.v1.BeaconStateZond.fork:type_name -> theqrl.qrl.v1.Fork
	14, // 2: theqrl.qrl.v1.BeaconStateZond.latest_block_header:type_name -> theqrl.qrl.v1.BeaconBlockHeader
	15, // 3: theqrl.qrl.v1.BeaconStateZond.execution_data:type_name -> theqrl.qrl.v1.ExecutionData
	15, // 4: theqrl.qrl.v1.BeaconStateZond.execution_data_votes:type_name -> theqrl.qrl.v1.ExecutionData
	16, // 5: theqrl.qrl.v1.BeaconStateZond.validators:type_name -> theqrl.qrl.v1.Validator
	17, // 6: theqrl.qrl.v1.BeaconStateZond.previous_justified_checkpoint:type_name -> theqrl.qrl.v1.Checkpoint
	17, // 7: theqrl.qrl.v1.BeaconStateZond.current_justified_checkpoint:type_name -> theqrl.qrl.v1.Checkpoint
	17, // 8: theqrl.qrl.v1.BeaconStateZond.finalized_checkpoint:type_name -> theqrl.qrl.v1.Checkpoint
	18, // 9: theqrl.qrl.v1.BeaconStateZond.current_sync_committee:type_name -> theqrl.qrl.v1.SyncCommittee
	18, // 10: theqrl.qrl.v1.BeaconStateZond.next_sync_committee:type_name -> theqrl.qrl.v1.SyncCommittee
	19, // 11: theqrl.qrl.v1.BeaconStateZond.latest_execution_payload_header:type_name -> theqrl.engine.v1.ExecutionPayloadHeaderZond
	4,  // 12: theqrl.qrl.v1.BeaconStateZond.historical_summaries:type_name -> theqrl.qrl.v1.HistoricalSummary
	20, // 13: theqrl.qrl.v1.BeaconStateResponse.version:type_name -> theqrl.qrl.v1.Version
	7,  // 14: theqrl.qrl.v1.BeaconStateResponse.data:type_name -> theqrl.qrl.v1.BeaconStateContainer
	3,  // 15: theqrl.qrl.v1.BeaconStateContainer.zond_state:type_name -> theqrl.qrl.v1.BeaconStateZond
	9,  // 16: theqrl.qrl.v1.ForkChoiceHeadsResponse.data:type_name -> theqrl.qrl.v1.ForkChoiceHead
	12, // 17: theqrl.qrl.v1.RandaoResponse.data:type_name -> theqrl.qrl.v1.RandaoResponse.Randao
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_qrl_v1_beacon_state_proto_init() }
func file_proto_qrl_v1_beacon_state_proto_init() {
	if File_proto_qrl_v1_beacon_state_proto != nil {
		return
	}
	file_proto_qrl_v1_attestation_proto_init()
	file_proto_qrl_v1_beacon_block_proto_init()
	file_proto_qrl_v1_validator_proto_init()
	file_proto_qrl_v1_sync_committee_proto_init()
	file_proto_qrl_v1_version_proto_init()
	file_proto_qrl_v1_beacon_state_proto_msgTypes[7].OneofWrappers = []any{
		(*BeaconStateContainer_ZondState)(nil),
	}
	file_proto_qrl_v1_beacon_state_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_qrl_v1_beacon_state_proto_rawDesc), len(file_proto_qrl_v1_beacon_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_qrl_v1_beacon_state_proto_goTypes,
		DependencyIndexes: file_proto_qrl_v1_beacon_state_proto_depIdxs,
		MessageInfos:      file_proto_qrl_v1_beacon_state_proto_msgTypes,
	}.Build()
	File_proto_qrl_v1_beacon_state_proto = out.File
	file_proto_qrl_v1_beacon_state_proto_goTypes = nil
	file_proto_qrl_v1_beacon_state_proto_depIdxs = nil
}
