name: Go build, vet and test

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-vet:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Build
        run: hack/go-test.sh build

      - name: Vet
        run: hack/go-test.sh vet

  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 120
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Test
        run: hack/go-test.sh test
