name: Test

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 120
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Bazel cache
        uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: true
          disk-cache: ci-qrysm-${{ runner.os }}-${{ runner.arch }}
          repository-cache: true

      - name: Test
        run: bazel test //... --test_output=errors --keep_going
